runtime: nodejs16
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    
entrypoint: node server.js

