# create a app.yaml file for gcloud deploymenet of a flask app with requirements.txt (5 lines). ChatGPT, 4 Sep. version, OpenAI, 01 Oct. 2023, chat.openai.com/chat.
runtime: python311
instance_class: F1
entrypoint: gunicorn -b :${PORT:-8080} server.main:app

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 0
  max_instances: 2

env_variables:
  PORT: "8080"