runtime: python311
instance_class: F1
entrypoint: gunicorn -b :${PORT:-8080} main:app

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 0
  max_instances: 2

env_variables:
  PORT: "8080"